Infinite Benchy Theorem:
  title: "Infinite Benchy Theorem"
  description: "A belted, enclosed 3D printer designed for 24/7 3D printing"
  repository: "https://raw.githubusercontent.com/qcoral/infinite-benchy-theorem/refs/heads/main/design.md"
  file_name: infinite_benchy_theorem.md
Radeon:
  title: "Radeon"
  description: "A budget-friendly printer designed around CoreXY kinematics and linear rails."
  repository: "https://raw.githubusercontent.com/pmnlla/radeon/refs/heads/master/docs-head.md"
  file_name: pmnlla-radeon.md
Quantum One:
  title: "Quantum One"
  description: "An affordable prototyping machine that looks good, performs well, is affordable, and you can build yourself"
  repository: "https://raw.githubusercontent.com/Echo-Labs-Development/Quantum-One/main/plan.md"
  file_name: quantum-one.md
## Add your printers below
