Infinite Benchy Theorem:
  title: "Infinite Benchy Theorem"
  description: "A belted, enclosed 3D printer designed for 24/7 3D printing"
  repository: "https://raw.githubusercontent.com/qcoral/infinite-benchy-theorem/refs/heads/main/design.md"
  file_name: infinite_benchy_theorem.md
Radeon:
  title: "Radeon"
  description: "A budget-friendly printer designed around CoreXY kinematics and linear rails."
  repository: "https://raw.githubusercontact.com/pmnlla/radeon/refs/heads/master/docs-head.md"
  file_name: pmnlla-radeon.md
## Add your printers below
